Repository Chartes-TNAH/TNAHBox, pull requests merged in 2019-03, with the labels that each got.

#14 Comptes utilisateurs #5
  app/modeles/donnees.py
  app/modeles/utilisateurs.py
  app/routes/__init__.py
  app/routes/routes.py
  app/templates/conteneur.html
  app/templates/pages/connexion.html
  app/templates/pages/inscription.html
  db.sqlite
Labels: enhancement

#19 Dev annuaire #10
  app/routes/routes.py
  app/templates/pages/annuaire.html
  app/templates/pages/person.html
Labels: Bonus

#27 Correction d'un bug lors de l'enregistrement
  app/routes/routes.py
  db.sqlite
Labels: bug

#42 Correction de bugs
  .DS_Store
  app/routes/routes.py
  app/static/img/pict_cv.png
  app/static/uploads/Biblio_webo.png
  app/static/uploads/CV_ALBOUY_Segolene.pdf
  app/static/uploads/Capture_decran_2019-03-19_a_20.01.10.png
  app/static/uploads/Capture_decran_2019-03-19_a_20.01.31.png
  app/templates/pages/accueil.html
  app/templates/pages/annuaire.html
  app/templates/pages/document.html
  app/templates/pages/import.html
  app/templates/pages/person.html
  app/templates/pages/profile.html
  app/templates/pages/recherche.html
  app/test_db.sqlite
  db.sqlite
Labels: bug
